Repository cse110-fa22-group22/cse110-fa22-group22, pull requests merged in 2022-11, with the labels that each got.

#29 Folder Hierarchy
  source/css/.css
  source/html/index.html
  source/javascript/.js
Labels: Task

#40 Fixed import and export
  source/javascript/index.js
  source/javascript/shopping/create.js
  source/javascript/shopping/delete.js
  source/javascript/shopping/test.js
  source/javascript/shopping/update.js
Labels: bug

#43 Scrolling List
  source/css/style.css
  source/html/index.html
Labels: Task

#48 Created eslintrc
  source/javascript/.eslintrc
Labels: enhancement

#65 Added Push/Pull Request Action Description
  admin/cipipeline/phase1.md
Labels: documentation

#66 Writeup updates
  admin/cipipeline/CICDPipelineWriteup.md
  admin/cipipeline/phase1.md
Labels: documentation

#72 Added babel and fixed removed package-lock.json from gitignore
  .gitignore
  source/.babelrc
  source/package-lock.json
  source/package.json
Labels: bug

#45 Shopping List: Create Method
  source/css/style.css
  source/html/index.html
  source/javascript/index.js
  source/javascript/jest/shopping-create.test.js
  source/javascript/shopping/create.js
Labels: Task

#77 Inventory List: Create Method
  source/javascript/inventory/create.js
  source/javascript/jest/inventory-create.test.js
Labels: Task

#85 69 task shopping list update item UI
  source/css/style.css
  source/html/index.html
  source/javascript/index.js
  source/javascript/shopping/create.js
Labels: Task

#105 Fixed create method's duplicated item error
  source/javascript/inventory/create.js
  source/javascript/jest/inventory-create.test.js
Labels: bug

#109 Added eslint for inventory files
  source/package.json
Labels: enhancement

#119 118 task inventory list create UI
  source/css/style.css
  source/html/index.html
  source/javascript/index.js
  source/javascript/inventory/create.js
  source/javascript/inventory/delete.js
  source/javascript/inventory/get.js
  source/javascript/inventory/update.js
  source/javascript/jest/inventory-delete.test.js
  source/javascript/jest/inventory-get.test.js
  source/javascript/jest/inventory-update.test.js
Labels: Task

#121 120 task inventory list update UI
  source/css/style.css
  source/html/index.html
  source/javascript/index.js
  source/javascript/inventory/create.js
  source/javascript/inventory/delete.js
  source/javascript/inventory/get.js
  source/javascript/inventory/update.js
  source/javascript/jest/inventory-delete.test.js
  source/javascript/jest/inventory-get.test.js
  source/javascript/jest/inventory-update.test.js
Labels: Task

#125 124 task inventory list get item method
  source/css/style.css
  source/html/index.html
  source/javascript/index.js
  source/javascript/inventory/create.js
  source/javascript/inventory/delete.js
  source/javascript/inventory/get.js
  source/javascript/inventory/update.js
  source/javascript/jest/inventory-delete.test.js
  source/javascript/jest/inventory-get.test.js
  source/javascript/jest/inventory-update.test.js
Labels: Task

#131 107 task inventory list generate list
  source/css/style.css
  source/html/index.html
  source/javascript/index.js
  source/javascript/inventory/create.js
  source/javascript/inventory/delete.js
  source/javascript/inventory/get.js
  source/javascript/inventory/update.js
  source/javascript/jest/inventory-delete.test.js
  source/javascript/jest/inventory-get.test.js
  source/javascript/jest/inventory-update.test.js
Labels: Task

#127 126 task shopping list improve create and update method
  source/javascript/index.js
Labels: Task

#128 123 task shopping list bought item UI
  source/css/style.css
  source/javascript/index.js
Labels: Task

#135 Phase2 pipeline
  admin/cipipeline/Pipelinediagram.png
  admin/cipipeline/phase1.md
  admin/cipipeline/phase1.png
  admin/cipipeline/phase2.md
  admin/cipipeline/phase2.png
Labels: Task
